[package]
name = "ta-ko-ho/should-single-name"
version = "0.1.1"
description = "wasmer-tests/wasmer-edge-svelte-sample website"

[dependencies]
"wasmer/static-web-server" = "*"

[fs]
public = "build"
